--------------------------------------------------------
--  File created - wtorek-października-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SYS"."COUNTRIES" 
   (    "COUNTRYID" NUMBER(*,0), 
    "NAME" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "SYS"."EVENTS" 
   (    "EVENTID" NUMBER(*,0), 
    "NAME" VARCHAR2(64 BYTE), 
    "DESCRIPTION" VARCHAR2(255 BYTE), 
    "EVENTDATE" DATE, 
    "PLACEID" NUMBER(*,0), 
    "GROUPID" NUMBER(*,0), 
    "OWNERID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "SYS"."PARTICIPANTS" 
   (    "PARTICIPANTID" NUMBER(*,0), 
    "NAME" VARCHAR2(64 BYTE), 
    "SURNAME" VARCHAR2(64 BYTE), 
    "BIRTHDATE" DATE, 
    "SEX" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLACES
--------------------------------------------------------

  CREATE TABLE "SYS"."PLACES" 
   (    "PLACEID" NUMBER(*,0), 
    "NAME" VARCHAR2(64 BYTE), 
    "ADDRESS" VARCHAR2(64 BYTE), 
    "CITY" VARCHAR2(64 BYTE), 
    "COLUMN1" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."RESERVATIONS" 
   (    "RESERVATIONID" NUMBER(*,0), 
    "RESERVATIONDATE" DATE, 
    "ISPAID" NUMBER(1,0) DEFAULT 0, 
    "PARTICIPANTID" NUMBER(*,0), 
    "EVENTID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONSSEATS
--------------------------------------------------------

  CREATE TABLE "SYS"."RESERVATIONSSEATS" 
   (    "SEATID" NUMBER(*,0), 
    "RESERVATIONID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEATS
--------------------------------------------------------

  CREATE TABLE "SYS"."SEATS" 
   (    "SEATID" NUMBER(*,0), 
    "SEATNUMBER" NUMBER(*,0), 
    "SEATROW" NUMBER(*,0), 
    "ISSTANDING" NUMBER(1,0) DEFAULT 0, 
    "SECTORID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SECTORS
--------------------------------------------------------

  CREATE TABLE "SYS"."SECTORS" 
   (    "SECTORID" NUMBER(*,0), 
    "NAME" VARCHAR2(64 BYTE), 
    "PLACEID" NUMBER(*,0), 
    "COLOURID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.COUNTRIES
SET DEFINE OFF;
Insert into SYS.COUNTRIES (COUNTRYID,NAME) values ('1','Polska');
Insert into SYS.COUNTRIES (COUNTRYID,NAME) values ('2','Biaorus');
REM INSERTING into SYS.EVENTS
SET DEFINE OFF;
REM INSERTING into SYS.PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into SYS.PLACES
SET DEFINE OFF;
REM INSERTING into SYS.RESERVATIONS
SET DEFINE OFF;
REM INSERTING into SYS.RESERVATIONSSEATS
SET DEFINE OFF;
REM INSERTING into SYS.SEATS
SET DEFINE OFF;
REM INSERTING into SYS.SECTORS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SYS"."COUNTRIES" MODIFY ("COUNTRYID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COUNTRIES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."EVENTS" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EVENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EVENTS" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EVENTS" MODIFY ("PLACEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EVENTS" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EVENTS" MODIFY ("OWNERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "SYS"."PARTICIPANTS" MODIFY ("PARTICIPANTID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTICIPANTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTICIPANTS" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTICIPANTS" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTICIPANTS" MODIFY ("SEX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLACES
--------------------------------------------------------

  ALTER TABLE "SYS"."PLACES" MODIFY ("PLACEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PLACES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PLACES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PLACES" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PLACES" MODIFY ("COLUMN1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."RESERVATIONS" MODIFY ("RESERVATIONID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RESERVATIONS" MODIFY ("RESERVATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RESERVATIONS" MODIFY ("ISPAID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RESERVATIONS" MODIFY ("PARTICIPANTID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RESERVATIONS" MODIFY ("EVENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATIONSSEATS
--------------------------------------------------------

  ALTER TABLE "SYS"."RESERVATIONSSEATS" MODIFY ("SEATID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RESERVATIONSSEATS" MODIFY ("RESERVATIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEATS
--------------------------------------------------------

  ALTER TABLE "SYS"."SEATS" MODIFY ("SEATID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEATS" MODIFY ("SEATNUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEATS" MODIFY ("SEATROW" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEATS" MODIFY ("ISSTANDING" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEATS" MODIFY ("SECTORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SECTORS
--------------------------------------------------------

  ALTER TABLE "SYS"."SECTORS" MODIFY ("SECTORID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SECTORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SECTORS" MODIFY ("PLACEID" NOT NULL ENABLE);
