--------------------------------------------------------
--  File created - niedziela-listopada-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "HR"."CATEGORIES" 
   (	"CATEGORYID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"PARENTID" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table COLOURS
--------------------------------------------------------

  CREATE TABLE "HR"."COLOURS" 
   (	"COLOURID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"HEX" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "HR"."COUNTRIES" 
   (	"COUNTRYID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "HR"."EVENTS" 
   (	"EVENTID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"EVENTDATE" DATE, 
	"PLACEID" NUMBER(*,0), 
	"GROUPID" NUMBER(*,0), 
	"OWNERID" NUMBER(*,0), 
	"CATEGORYID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table EVENTSGROUPS
--------------------------------------------------------

  CREATE TABLE "HR"."EVENTSGROUPS" 
   (	"GROUPID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"OWNERID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table OWNERS
--------------------------------------------------------

  CREATE TABLE "HR"."OWNERS" 
   (	"OWNERID" NUMBER(*,0), 
	"NIP" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"ADDRESS" VARCHAR2(64 BYTE), 
	"CITY" VARCHAR2(64 BYTE), 
	"FOUNDATIONDATE" DATE, 
	"COUNTRYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "HR"."PARTICIPANTS" 
   (	"PARTICIPANTID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"SURNAME" VARCHAR2(64 BYTE), 
	"BIRTHDATE" DATE, 
	"SEX" CHAR(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table PLACES
--------------------------------------------------------

  CREATE TABLE "HR"."PLACES" 
   (	"PLACEID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"ADDRESS" VARCHAR2(64 BYTE), 
	"CITY" VARCHAR2(64 BYTE), 
	"COUNTRYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "HR"."RESERVATIONS" 
   (	"RESERVATIONID" NUMBER(*,0), 
	"RESERVATIONDATE" DATE, 
	"ISPAID" NUMBER(1,0) DEFAULT 0, 
	"PARTICIPANTID" NUMBER(*,0), 
	"EVENTID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONSSEATS
--------------------------------------------------------

  CREATE TABLE "HR"."RESERVATIONSSEATS" 
   (	"SEATID" NUMBER(*,0), 
	"RESERVATIONID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table SEATS
--------------------------------------------------------

  CREATE TABLE "HR"."SEATS" 
   (	"SEATID" NUMBER(*,0), 
	"SEATNUMBER" NUMBER(*,0), 
	"SEATROW" NUMBER(*,0), 
	"ISSTANDING" NUMBER(1,0) DEFAULT 0, 
	"SECTORID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table SECTORS
--------------------------------------------------------

  CREATE TABLE "HR"."SECTORS" 
   (	"SECTORID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"PLACEID" NUMBER(*,0), 
	"COLOURID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

  CREATE TABLE "HR"."TICKETS" 
   (	"TICKETID" NUMBER(*,0), 
	"PRICE" NUMBER(7,2), 
	"SECTORID" NUMBER(*,0), 
	"EVENTID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "HR"."CATEGORIES" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "HR"."CATEGORIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."CATEGORIES" MODIFY ("PARENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLOURS
--------------------------------------------------------

  ALTER TABLE "HR"."COLOURS" MODIFY ("COLOURID" NOT NULL ENABLE);
  ALTER TABLE "HR"."COLOURS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."COLOURS" MODIFY ("HEX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "HR"."COUNTRIES" MODIFY ("COUNTRYID" NOT NULL ENABLE);
  ALTER TABLE "HR"."COUNTRIES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "HR"."EVENTS" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTS" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTS" MODIFY ("PLACEID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTS" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTS" MODIFY ("OWNERID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTS" MODIFY ("CATEGORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTSGROUPS
--------------------------------------------------------

  ALTER TABLE "HR"."EVENTSGROUPS" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTSGROUPS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTSGROUPS" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTSGROUPS" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."EVENTSGROUPS" MODIFY ("OWNERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OWNERS
--------------------------------------------------------

  ALTER TABLE "HR"."OWNERS" MODIFY ("OWNERID" NOT NULL ENABLE);
  ALTER TABLE "HR"."OWNERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."OWNERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HR"."OWNERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "HR"."OWNERS" MODIFY ("COUNTRYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "HR"."PARTICIPANTS" MODIFY ("PARTICIPANTID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PARTICIPANTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."PARTICIPANTS" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."PARTICIPANTS" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PARTICIPANTS" MODIFY ("SEX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLACES
--------------------------------------------------------

  ALTER TABLE "HR"."PLACES" MODIFY ("PLACEID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLACES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLACES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLACES" MODIFY ("CITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "HR"."RESERVATIONS" MODIFY ("RESERVATIONID" NOT NULL ENABLE);
  ALTER TABLE "HR"."RESERVATIONS" MODIFY ("RESERVATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."RESERVATIONS" MODIFY ("ISPAID" NOT NULL ENABLE);
  ALTER TABLE "HR"."RESERVATIONS" MODIFY ("PARTICIPANTID" NOT NULL ENABLE);
  ALTER TABLE "HR"."RESERVATIONS" MODIFY ("EVENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATIONSSEATS
--------------------------------------------------------

  ALTER TABLE "HR"."RESERVATIONSSEATS" MODIFY ("SEATID" NOT NULL ENABLE);
  ALTER TABLE "HR"."RESERVATIONSSEATS" MODIFY ("RESERVATIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEATS
--------------------------------------------------------

  ALTER TABLE "HR"."SEATS" MODIFY ("SEATID" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEATS" MODIFY ("SEATNUMBER" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEATS" MODIFY ("SEATROW" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEATS" MODIFY ("ISSTANDING" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEATS" MODIFY ("SECTORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SECTORS
--------------------------------------------------------

  ALTER TABLE "HR"."SECTORS" MODIFY ("SECTORID" NOT NULL ENABLE);
  ALTER TABLE "HR"."SECTORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."SECTORS" MODIFY ("PLACEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "HR"."TICKETS" MODIFY ("TICKETID" NOT NULL ENABLE);
  ALTER TABLE "HR"."TICKETS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."TICKETS" MODIFY ("SECTORID" NOT NULL ENABLE);
  ALTER TABLE "HR"."TICKETS" MODIFY ("EVENTID" NOT NULL ENABLE);
